/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import java.sql.*;
import Controller.PersonaControlador;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author karen
 */
public class VistaBuscarUsuario extends javax.swing.JInternalFrame {

    private PersonaControlador personaControlador;
    private boolean pacienteEncontrado = false;
    private ResultSet rs;
    /**
     * Creates new form SearchUserView
     */
    public VistaBuscarUsuario(PersonaControlador personaControlador) {
        initComponents();
        this.personaControlador = personaControlador;
        btnGuardar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        btnSeleccionarPaciente = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnExitSearchUser = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel8.setText("BUSCAR PACIENTE");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Cédula");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Fecha de nacimiento");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Género");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Correro Electrónico");

        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCedula.setToolTipText("XXXXXXXXXX");
        txtCedula.setName("cnb"); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtNombre.setEditable(false);
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtFecha.setToolTipText("");

        txtCorreo.setEditable(false);
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreo.setToolTipText("");

        generos.add(masculino);
        masculino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        masculino.setText("Masculino");
        masculino.setEnabled(false);

        generos.add(femenino);
        femenino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        femenino.setText("Femenino");
        femenino.setEnabled(false);
        femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femeninoActionPerformed(evt);
            }
        });

        btnSeleccionarPaciente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeleccionarPaciente.setText("Seleccionar Usuario");
        btnSeleccionarPaciente.setActionCommand("Seleccionar Paciente");
        btnSeleccionarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPacienteActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnExitSearchUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExitSearchUser.setText("Salir");
        btnExitSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitSearchUserActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Apellido");

        txtApellido.setEditable(false);
        txtApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtApellido.setToolTipText("");

        btnGuardar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(masculino)
                                                .addGap(18, 18, 18)
                                                .addComponent(femenino))
                                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                            .addComponent(txtFecha)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                                            .addComponent(txtNombre)
                                            .addComponent(txtApellido)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(btnSeleccionarPaciente)
                                        .addGap(63, 63, 63)
                                        .addComponent(btnEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                        .addComponent(btnLimpiar)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscar)
                                    .addComponent(btnGuardar))))
                        .addGap(0, 133, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExitSearchUser)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardar)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(masculino)
                            .addComponent(femenino))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarPaciente)
                    .addComponent(btnEditar)
                    .addComponent(btnLimpiar))
                .addGap(26, 26, 26)
                .addComponent(btnExitSearchUser)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femeninoActionPerformed

    private void btnExitSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitSearchUserActionPerformed
        borrarCampos();
        cambiarEditable(false);
        txtCedula.setEditable(true);
        dispose();
    }//GEN-LAST:event_btnExitSearchUserActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        if(txtCedula.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No se ha ingresado ninguna cédula");
        }else{
            if(comprobarCedula(txtCedula.getText())){
                pacienteEncontrado = true;
                rs = personaControlador.buscarPaciente(txtCedula.getText());
                
                try {
                    if (rs.next()) { // Verifica si hay al menos una fila de resultados
                        txtApellido.setText(rs.getString("apellido"));
                        txtCorreo.setText(rs.getString("email"));
                        txtFecha.setText(rs.getString("fechaNacimiento"));
                        txtNombre.setText(rs.getString("nombre"));
                        int codigoGenero = rs.getInt("codigoGenero");

                        selectGender(personaControlador.devolverGenero(codigoGenero));
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "No se encontró ningun paciente");
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(VistaBuscarUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }


            }else{
                txtCedula.setText("");
            }
        }
        
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        borrarCampos();
        txtCedula.setEditable(true);
        cambiarEditable(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(pacienteEncontrado){
            cambiarEditable(true);
            btnGuardar.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(rootPane, "No existe un paciente buscado");
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSeleccionarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPacienteActionPerformed
        if(pacienteEncontrado){
            VistaPrincipal.txtCedula.setText(txtCedula.getText());
            VistaPrincipal.txtNombre.setText(txtApellido.getText() + " " +txtNombre.getText());
            VistaPrincipal.pacienteSeleccionado = true;
        }else{
            JOptionPane.showMessageDialog(rootPane, "No existe el paciente buscado");
        }
    }//GEN-LAST:event_btnSeleccionarPacienteActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(comprobarCampos() && comprobarCedula(txtCedula.getText())){
            try {
                boolean editado = personaControlador.editarPersona(txtCedula.getText(), txtNombre.getText(), txtApellido.getText(), txtFecha.getText(), txtCorreo.getText(), getSelectedButtonText(generos), rs.getInt("codigoPaciente"));
                if(editado){
                    JOptionPane.showMessageDialog(rootPane, "Información del paciente editada corrrectamento");
                    borrarCampos();
                    cambiarEditable(false);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "No se pudo editar lal información del paciente");
                }
            } catch (SQLException ex) {
                Logger.getLogger(VistaBuscarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    private String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (var enumeration = buttonGroup.getElements(); enumeration.hasMoreElements();) {
            AbstractButton button = enumeration.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }
    
    public boolean comprobarCedula(String cedula) {
        // Verificar que la cédula tenga exactamente 10 dígitos
        if (cedula == null || cedula.length() != 10) {
            JOptionPane.showMessageDialog(rootPane, "Cedula incorrecta, son 10 dígitos");
            return false;
        }

        try {
            int provincia = Integer.parseInt(cedula.substring(0, 2));
            int digitoVerificador = Integer.parseInt(cedula.substring(9, 10));

            // Verificar que los primeros dos dígitos (provincia) estén en el rango 00-24
            if (provincia < 0 || provincia > 24) {
                JOptionPane.showMessageDialog(rootPane, "Cedula incorrecta");
                return false;
            }

            int[] coeficientes = {2, 1, 2, 1, 2, 1, 2, 1, 2};
            int suma = 0;

            // Calcular la suma de los productos según los coeficientes
            for (int i = 0; i < 9; i++) {
                int digito = Integer.parseInt(cedula.substring(i, i + 1));
                int producto = digito * coeficientes[i];
                suma += (producto >= 10) ? producto - 9 : producto;
            }

            // Calcular el dígito verificador
            int digitoCalculado = (suma % 10 == 0) ? 0 : 10 - (suma % 10);

            if(digitoVerificador == digitoCalculado){
                return true;
            }else{
                JOptionPane.showMessageDialog(rootPane, "Cedula incorrecta");
                txtCedula.setText("");
                return false;
            }

        } catch (NumberFormatException e) {
            // La cédula contiene caracteres no numéricos
            JOptionPane.showMessageDialog(rootPane, "Cedula incorrecta, ingrese solo números");
            return false;
        }
    }
    
    public void selectGender(String gender) {
        if (gender.equalsIgnoreCase("Masculino")) {
            masculino.setSelected(true);
        } else if (gender.equalsIgnoreCase("Femenino")) {
            femenino.setSelected(true);
        }
    }
    
    private void borrarCampos(){
        txtApellido.setText("");
        txtCedula.setText("");
        txtCorreo.setText("");
        txtFecha.setText("");
        txtNombre.setText("");
        generos.clearSelection();
    }
    
    private void cambiarEditable(boolean editable){
        txtApellido.setEditable(editable);
        txtCorreo.setEditable(editable);
        txtFecha.setEditable(editable);
        txtNombre.setEditable(editable);
        masculino.setEnabled(editable);
        femenino.setEnabled(editable);
    }
    
    private boolean comprobarCampos(){
        if(txtApellido.getText().equals("") || txtCedula.getText().equals("") || txtCorreo.getText().equals("") || txtFecha.getText().equals("") || txtNombre.getText().equals("") || (femenino.isSelected()== false && masculino.isSelected()== false)){
            JOptionPane.showMessageDialog(rootPane, "Llene todos los campos");
            return false;
        }else{
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExitSearchUser;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSeleccionarPaciente;
    private javax.swing.JRadioButton femenino;
    private javax.swing.ButtonGroup generos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
